url: https://ptolvane.github.io
baseurl: 

# Site settings
title: Pekka Tolvanen
email: pekka.tolvanen@sange.fi
description: "Pekka Tolvanen's portfolio"


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/pekka-tolvanen/
  - title: instagram
    url: https://www.instagram.com/durbu/
  - title: facebook
    url: https://www.facebook.com/pekka.tolvanen/

# Postal address (add as many lines as necessary)
address:


# Build settings
markdown: kramdown
permalink: pretty
